apiVersion: v1
kind: Pod
metadata:
  name: "myapp"
  namespace: default
  labels:
    app: "webapp_flask"
spec:
  containers:
  - name: myapp-web
    image: "learndevops29/learndocker29:mywebapp"
    ports:
    - containerPort:  8080
      name:  http
    