apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp-rc
    type: front-end
spec:

  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
        type: front-end
    spec:
      containers:
        - name: redis-container
          image: redis
  replicas: 3
    matchLabels: 
      app: myapp-pod
