apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort   #Nodeport which will be accessible from outside POD
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004   #range30000 to 32767
  selector:
        app: myapp

