apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: front-end
    app: nginx
spec:
  selector:
      matchLabels:
        app: myapp #pod lable match 1
  replicas: 3
  template:
    metadata:  # Pod meta data
      name: nginx-pod_deployment
      labels:
        app: myapp # POD Lable which is matching in replcia set 1
    spec:   #pod container specifiacation 
      containers:
        - name: nginx-container 
          image: nginx  

