apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb-srv
  name: myweb-srv
spec:
  ports:
  - name: 80-5000
    port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30080
  selector:
    app: webserver
    tool: flask 
  type: NodePort
status:
  loadBalancer: {}
